Server:
    ServeFrom: localhost
    Address: 127.0.0.1
    Port: 9998
Recording:
    Cameras:
        - 0
        - 1
        - 7
    Microphones:
        - 0
        - 1
        - 3
    SID: None
    RecFolder: /mnt/recordings/
Hardware:
    SearchStringAudio: HD_Pro
