Server:
    Address: 127.0.0.1
    Port: 9998
Recording:
    Cameras:
        - 0
        - 2
        - 3
    Microphones:
        - 0
        - 1
        - 3
    SID: None
    RecFolder: /run/media/andrews/iso
