// A simple taskmanager that operates on a channel
package taskqueue

import (
    "bitbucket.com/andrews2000/multicam/recordcontrol"
    "fmt"
    //"strconv"
)

type TaskQueue struct {
    Queue chan Task
}

// Execute tasks until stopping channel is true
func (tq TaskQueue) ExecuteTask(rc *recordcontrol.RecordControl) {
    for {
        cmd := <-tq.Queue
        cmdType := cmd.Command

        fmt.Println("TQ: "+cmdType)

        switch cmdType  {
        case "GetState":
            cmd.FeedbackChannel <- rc.TaskGetStatus()
        case "GetConfig":
            cmd.FeedbackChannel <- rc.TaskGetConfig()
        case "SetConfig":
            //cmd.FeedbackChannel <- rc.TaskSetConfig(cmd.Data)
        case "Preflight":
            //TODO Execute command on recordcontrol (e.g. rc.GetState(cmd.FeedbackChannel)
        case "StartRecording":
            //TODO Execute command on recordcontrol (e.g. rc.GetState(cmd.FeedbackChannel)
        case "StopRecording":
            //TODO Execute command on recordcontrol (e.g. rc.GetState(cmd.FeedbackChannel)
            //TODO Check first if possible
        case "Error":
            //TODO run error handling function of task queue
        case "ReturnError":
            //TODO Execute command on recordcontrol (e.g. rc.GetState(cmd.FeedbackChannel)
        default:
            //TODO Some sort of error handling
        }
    }
}

// A command generated by one of the servers
type Task struct {
    // The type of the command
    Command string
    // The "content" of the command
    // nil for control commands and state requests
    // ConfigStruct for Config requests
    // String for error messages
    //TODO Clarify: String or Struct for data commands (containing trigger information)
    // Command of recordcontrol asserts the interface into the expected type for that command
    Data interface{}
    //TODO Include the use of the timestamp object
    // Feedback channel for the response of the client
    FeedbackChannel chan []byte
}

// Data representing the configuration as set by the user
type DataConfig struct {
    // Cameras to record from
    Camera_ids []int
    // Microphones to record from
    Microphone_ids []int
    // Location to record to
    Recording_location string
    // Id of the subject
    Subject_id string
}
